name: actions
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    
    env:
      MIX_ENV: test
      
    services:
      db:
        image: postgres:11.5-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.2'
          elixir-version: '1.12.0'
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: mix do deps.get, deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix do ecto.create, ecto.migrate
      - run: mix test
      - run: mix format --check-formatted
      - run: mix credo --strict
